---
upload_path: "/img/article/:year:"
frontmatter_file_url_template: "/img/article/:year:"
body_file_url_template: "/img/article/:year:"
new_page_extension: md
auto_deploy: true
admin_path: 
webhook_url: 
collections: 
